version: '3'
services:
  livematches-service:
    image: "livematches-service-prod"
    container_name: "livematches-service-prod"
    build:
      context: .
      args:
        - mHost=iafoosball.me
        - mPort=9000
    ports:
      - 9003:8003
    - volumes:
      - /var/lib/iafoosball/certs:/