package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Match match
// swagger:model Match
type Match struct {

	// The match id which is the collection + "/" + the key
	ID string `json:"_id,omitempty"`

	// The match key
	Key string `json:"_key,omitempty"`

	// This is the user id of the first player playing on the blue side.
	BlueOneID string `json:"blue_one_id,omitempty"`

	// The position of the blue user 1. As this can vary during a game, use the notatation datetime\position
	BlueOnePosition []string `json:"blue_one_position,omitempty"`

	// This is the user id of the second player playing on the blue side. (Not used in single)
	BlueTwoID string `json:"blue_two_id,omitempty"`

	// The position of the blue user 2. As this can vary during a game, use the notatation datetime\position
	BlueTwoPosition []string `json:"blue_two_position"`

	// Was the game completed.
	Completed bool `json:"completed,omitempty"`

	// the datetime when the match ends
	EndTime string `json:"end_time,omitempty"`

	// We only save the goal speed. So the goal speed counts as goal. We use zero as default value, for example if a goal is manually added. This could change in the future to maps, if we decide to save the scoring player as well
	GoalsBlue []float64 `json:"goals_blue"`

	// We only save the goal speed. So the goal speed counts as goal. We use zero as default value, for example if a goal is manually added.
	GoalsRed []float64 `json:"goals_red"`

	// The maximum number of goals for this game. If a time is specified the first criteria which is true will stop the match.
	MaxGoals *int64 `json:"max_goals,omitempty"`

	// The maximum tim in sec for this game. If a max goals is specified the first criteria which is true will stop the match.
	MaxTime int64 `json:"max_time,omitempty"`

	// A match can be rated, ie a ranked game with points, or without.
	RatedMatch bool `json:"rated_match,omitempty"`

	// This is the user id of the first player playing on the red side.
	RedOneID string `json:"red_one_id,omitempty"`

	// The position of the red user 1. As this can vary during a game, use the notatation datetime\position
	RedOnePosition []string `json:"red_one_position"`

	// This is the user id of the second player playing on the red side. (Not used in single)
	RedTwoID string `json:"red_two_id,omitempty"`

	// The position of the red user 2. As this can vary during a game, use the notatation datetime\position
	RedTwoPosition []string `json:"red_two_position"`

	// the datetime when the game ends
	StartTime string `json:"start_time,omitempty"`

	// Switch the position after 50% of the goal (time or goals) is reached.
	SwitchPosition bool `json:"switch_position,omitempty"`

	// Can be either "red" or "blue"
	Winner string `json:"winner,omitempty"`
}

// Validate validates this match
func (m *Match) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Match) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Match) UnmarshalBinary(b []byte) error {
	var res Match
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
